local M = {}

function M.get(p)
  local bg      = p.eerie_black
  local bg_alt  = p.jet
  local fg      = p.seasalt
  local muted   = p.cadet_gray
  local subtle  = p.gray
  local accent  = p.light_sea_green
  local string_ = p.ecru
  local literal = p.eggshell
  local err     = p.amaranth
  local err_dim = p.auburn

  return {
    -- Editor UI
    Normal        = { fg = fg, bg = bg },
    NormalFloat   = { fg = fg, bg = bg_alt },
    FloatBorder   = { fg = subtle, bg = bg_alt },
    FloatTitle    = { fg = accent, bg = bg_alt, bold = true },
    NormalNC      = { fg = fg, bg = bg },
    EndOfBuffer   = { fg = bg },
    SignColumn    = { bg = bg },
    LineNr        = { fg = subtle },
    CursorLineNr  = { fg = fg, bold = true },
    CursorLine    = { bg = bg_alt },
    CursorColumn  = { bg = bg_alt },
    ColorColumn   = { bg = bg_alt },
    Cursor        = { fg = bg, bg = fg },
    Visual        = { bg = bg_alt },
    VisualNOS     = { bg = bg_alt },
    MatchParen    = { fg = literal, bold = true, underline = true },
    NonText       = { fg = subtle },
    Whitespace    = { fg = bg_alt },
    SpecialKey    = { fg = subtle },
    Conceal       = { fg = muted },
    Directory     = { fg = accent },
    Title         = { fg = accent, bold = true },
    FoldColumn    = { fg = subtle, bg = bg },
    Folded        = { fg = muted, bg = bg_alt },

    -- Splits / status / tabs
    VertSplit     = { fg = bg_alt, bg = bg },
    WinSeparator  = { fg = bg_alt, bg = bg },
    StatusLine    = { fg = fg, bg = bg_alt },
    StatusLineNC  = { fg = muted, bg = bg_alt },
    TabLine       = { fg = muted, bg = bg_alt },
    TabLineSel    = { fg = fg, bg = bg, bold = true },
    TabLineFill   = { fg = muted, bg = bg_alt },
    WinBar        = { fg = fg, bg = bg },
    WinBarNC      = { fg = muted, bg = bg },

    -- Search / completion
    Search        = { fg = bg, bg = string_ },
    CurSearch     = { fg = bg, bg = err },
    IncSearch     = { fg = bg, bg = err },
    Substitute    = { fg = bg, bg = literal },
    Pmenu         = { fg = fg, bg = bg_alt },
    PmenuSel      = { fg = bg, bg = accent, bold = true },
    PmenuSbar     = { bg = bg_alt },
    PmenuThumb    = { bg = subtle },
    WildMenu      = { fg = bg, bg = accent },

    -- Messages
    ErrorMsg      = { fg = err, bold = true },
    WarningMsg    = { fg = string_, bold = true },
    ModeMsg       = { fg = fg, bold = true },
    MoreMsg       = { fg = accent, bold = true },
    Question      = { fg = accent },
    MsgArea       = { fg = fg, bg = bg },
    MsgSeparator  = { fg = subtle, bg = bg },

    -- Sugar-high parity (see app/globals.css on jdonghia.github.io)
    Identifier     = { fg = fg },
    Keyword        = { fg = accent },
    String         = { fg = string_ },
    Character      = { fg = string_ },
    Type           = { fg = accent },
    StorageClass   = { fg = accent },
    Structure      = { fg = accent },
    Typedef        = { fg = accent },
    Statement      = { fg = accent },
    Conditional    = { fg = accent },
    Repeat         = { fg = accent },
    Label          = { fg = accent },
    Exception      = { fg = accent },
    Include        = { fg = accent },
    Define         = { fg = accent },
    Macro          = { fg = accent },
    PreProc        = { fg = accent },
    PreCondit      = { fg = accent },
    Operator       = { fg = subtle },
    Delimiter      = { fg = subtle },
    Comment        = { fg = subtle, italic = true },
    SpecialComment = { fg = muted, italic = true },
    Function       = { fg = fg },
    Special        = { fg = literal },
    SpecialChar    = { fg = literal },
    Tag            = { fg = accent },
    Constant       = { fg = literal },
    Number         = { fg = literal },
    Float          = { fg = literal },
    Boolean        = { fg = literal },
    Todo           = { fg = bg, bg = string_, bold = true },
    Underlined     = { fg = accent, underline = true },
    Error          = { fg = err },

    -- Treesitter
    ["@variable"]            = { fg = fg },
    ["@variable.builtin"]    = { fg = literal, italic = true },
    ["@variable.parameter"]  = { fg = fg },
    ["@variable.member"]     = { fg = muted },
    ["@property"]            = { fg = muted },
    ["@field"]               = { fg = muted },
    ["@constant"]            = { fg = literal },
    ["@constant.builtin"]    = { fg = literal, italic = true },
    ["@constant.macro"]      = { fg = literal },
    ["@string"]              = { fg = string_ },
    ["@string.escape"]       = { fg = literal },
    ["@string.special"]      = { fg = literal },
    ["@character"]           = { fg = string_ },
    ["@number"]              = { fg = literal },
    ["@boolean"]             = { fg = literal },
    ["@float"]               = { fg = literal },
    ["@function"]            = { fg = fg },
    ["@function.builtin"]    = { fg = fg },
    ["@function.call"]       = { fg = fg },
    ["@function.macro"]      = { fg = accent },
    ["@function.method"]     = { fg = fg },
    ["@method"]              = { fg = fg },
    ["@method.call"]         = { fg = fg },
    ["@constructor"]         = { fg = accent },
    ["@parameter"]           = { fg = fg },
    ["@keyword"]             = { fg = accent },
    ["@keyword.function"]    = { fg = accent },
    ["@keyword.operator"]    = { fg = accent },
    ["@keyword.return"]      = { fg = accent },
    ["@keyword.import"]      = { fg = accent },
    ["@conditional"]         = { fg = accent },
    ["@repeat"]              = { fg = accent },
    ["@exception"]           = { fg = accent },
    ["@operator"]            = { fg = subtle },
    ["@punctuation"]         = { fg = subtle },
    ["@punctuation.bracket"] = { fg = subtle },
    ["@punctuation.delimiter"] = { fg = subtle },
    ["@punctuation.special"] = { fg = literal },
    ["@type"]                = { fg = accent },
    ["@type.builtin"]        = { fg = accent },
    ["@type.definition"]     = { fg = accent },
    ["@type.qualifier"]      = { fg = accent },
    ["@attribute"]           = { fg = accent },
    ["@namespace"]           = { fg = accent },
    ["@module"]              = { fg = accent },
    ["@symbol"]              = { fg = literal },
    ["@tag"]                 = { fg = accent },
    ["@tag.attribute"]       = { fg = muted },
    ["@tag.delimiter"]       = { fg = subtle },
    ["@comment"]             = { fg = subtle, italic = true },
    ["@comment.todo"]        = { fg = bg, bg = string_, bold = true },
    ["@comment.note"]        = { fg = bg, bg = accent, bold = true },
    ["@comment.warning"]     = { fg = bg, bg = string_, bold = true },
    ["@comment.error"]       = { fg = bg, bg = err, bold = true },
    ["@text"]                = { fg = fg },
    ["@text.title"]          = { fg = accent, bold = true },
    ["@text.literal"]        = { fg = string_ },
    ["@text.uri"]            = { fg = accent, underline = true },
    ["@text.reference"]      = { fg = literal },
    ["@text.emphasis"]       = { fg = fg, italic = true },
    ["@text.strong"]         = { fg = fg, bold = true },
    ["@text.strike"]         = { fg = muted, strikethrough = true },

    -- LSP semantic tokens
    ["@lsp.type.variable"]   = { fg = fg },
    ["@lsp.type.parameter"]  = { fg = fg },
    ["@lsp.type.property"]   = { fg = muted },
    ["@lsp.type.function"]   = { fg = fg },
    ["@lsp.type.method"]     = { fg = fg },
    ["@lsp.type.class"]      = { fg = accent },
    ["@lsp.type.type"]       = { fg = accent },
    ["@lsp.type.interface"]  = { fg = accent },
    ["@lsp.type.enum"]       = { fg = accent },
    ["@lsp.type.struct"]     = { fg = accent },
    ["@lsp.type.namespace"]  = { fg = accent },
    ["@lsp.type.keyword"]    = { fg = accent },
    ["@lsp.type.string"]     = { fg = string_ },
    ["@lsp.type.number"]     = { fg = literal },
    ["@lsp.type.comment"]    = { fg = subtle, italic = true },
    ["@lsp.type.operator"]   = { fg = subtle },
    ["@lsp.type.macro"]      = { fg = accent },
    ["@lsp.type.decorator"]  = { fg = accent },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = literal, italic = true },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = fg },

    -- Diagnostics
    DiagnosticError            = { fg = err },
    DiagnosticWarn             = { fg = string_ },
    DiagnosticInfo             = { fg = accent },
    DiagnosticHint             = { fg = muted },
    DiagnosticOk               = { fg = accent },
    DiagnosticUnderlineError   = { undercurl = true, sp = err },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = string_ },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = accent },
    DiagnosticUnderlineHint    = { undercurl = true, sp = muted },
    DiagnosticVirtualTextError = { fg = err, bg = bg },
    DiagnosticVirtualTextWarn  = { fg = string_, bg = bg },
    DiagnosticVirtualTextInfo  = { fg = accent, bg = bg },
    DiagnosticVirtualTextHint  = { fg = muted, bg = bg },

    -- Diff
    DiffAdd       = { fg = accent, bg = bg_alt },
    DiffChange    = { fg = string_, bg = bg_alt },
    DiffDelete    = { fg = err_dim, bg = bg_alt },
    DiffText      = { fg = err, bg = bg_alt, bold = true },
    ["@diff.plus"]  = { fg = accent },
    ["@diff.minus"] = { fg = err },
    ["@diff.delta"] = { fg = string_ },

    -- Spell
    SpellBad   = { undercurl = true, sp = err },
    SpellCap   = { undercurl = true, sp = accent },
    SpellLocal = { undercurl = true, sp = string_ },
    SpellRare  = { undercurl = true, sp = literal },

    -- Git signs / fugitive
    GitSignsAdd      = { fg = accent },
    GitSignsChange   = { fg = string_ },
    GitSignsDelete   = { fg = err },
    GitSignsAddNr    = { fg = accent },
    GitSignsChangeNr = { fg = string_ },
    GitSignsDeleteNr = { fg = err },
    GitGutterAdd     = { fg = accent },
    GitGutterChange  = { fg = string_ },
    GitGutterDelete  = { fg = err },
    diffAdded        = { fg = accent },
    diffRemoved      = { fg = err },
    diffChanged      = { fg = string_ },

    -- Telescope
    TelescopeNormal         = { fg = fg, bg = bg_alt },
    TelescopeBorder         = { fg = subtle, bg = bg_alt },
    TelescopePromptNormal   = { fg = fg, bg = bg_alt },
    TelescopePromptBorder   = { fg = subtle, bg = bg_alt },
    TelescopePromptTitle    = { fg = bg, bg = accent, bold = true },
    TelescopePreviewTitle   = { fg = bg, bg = accent, bold = true },
    TelescopeResultsTitle   = { fg = bg_alt, bg = bg_alt },
    TelescopeSelection      = { fg = bg, bg = accent, bold = true },
    TelescopeSelectionCaret = { fg = bg, bg = accent, bold = true },
    TelescopeMultiSelection = { fg = literal, bg = bg_alt, bold = true },
    TelescopeMultiIcon      = { fg = literal, bg = bg_alt },
    TelescopePreviewLine    = { bg = bg },
    TelescopeMatching       = { fg = err, bold = true },
    TelescopePromptPrefix   = { fg = accent },

    -- Snacks picker
    SnacksPicker                  = { fg = fg, bg = bg_alt },
    SnacksPickerBorder            = { fg = subtle, bg = bg_alt },
    SnacksPickerTitle             = { fg = bg, bg = accent, bold = true },
    SnacksPickerFooter            = { fg = muted, bg = bg_alt },
    SnacksPickerInput             = { fg = fg, bg = bg_alt },
    SnacksPickerInputBorder       = { fg = accent, bg = bg_alt },
    SnacksPickerInputTitle        = { fg = bg, bg = accent, bold = true },
    SnacksPickerInputCursorLine   = { bg = bg_alt },
    SnacksPickerList              = { fg = fg, bg = bg_alt },
    SnacksPickerListBorder        = { fg = subtle, bg = bg_alt },
    SnacksPickerListTitle         = { fg = bg, bg = accent, bold = true },
    SnacksPickerListCursorLine    = { fg = bg, bg = accent, bold = true },
    SnacksPickerCursorLine        = { fg = bg, bg = accent, bold = true },
    SnacksPickerSelected          = { fg = literal, bg = bg_alt, bold = true },
    SnacksPickerMatch             = { fg = err, bold = true },
    SnacksPickerPreview           = { fg = fg, bg = bg },
    SnacksPickerPreviewBorder     = { fg = subtle, bg = bg },
    SnacksPickerPreviewTitle      = { fg = bg, bg = accent, bold = true },
    SnacksPickerPreviewCursorLine = { bg = bg_alt },
    SnacksPickerPrompt            = { fg = accent, bg = bg_alt, bold = true },
    SnacksPickerDir               = { fg = muted },
    SnacksPickerFile              = { fg = fg },
    SnacksPickerPathHidden        = { fg = subtle },
    SnacksPickerPathIgnored       = { fg = subtle },
    SnacksPickerBufFlags          = { fg = string_ },
    SnacksPickerKeymap            = { fg = literal },
    SnacksPickerIcon              = { fg = accent },
    SnacksPickerIconDir           = { fg = accent },
    SnacksPickerIconFile          = { fg = muted },
    SnacksPickerGitStatus         = { fg = string_ },
    SnacksPickerGitStatusAdded    = { fg = accent },
    SnacksPickerGitStatusModified = { fg = string_ },
    SnacksPickerGitStatusDeleted  = { fg = err },
    SnacksPickerGitStatusRenamed  = { fg = literal },
    SnacksPickerGitStatusUntracked= { fg = muted },
    SnacksPickerToggle            = { fg = bg, bg = accent, bold = true },
    SnacksPickerSpecial           = { fg = literal },
    SnacksPickerDelim             = { fg = subtle },

    -- NvimTree / Neo-tree / Oil
    NvimTreeNormal             = { fg = fg, bg = bg },
    NvimTreeRootFolder         = { fg = accent, bold = true },
    NvimTreeFolderName         = { fg = fg },
    NvimTreeFolderIcon         = { fg = accent },
    NvimTreeOpenedFolderName   = { fg = accent, bold = true },
    NvimTreeGitDirty           = { fg = string_ },
    NvimTreeGitNew             = { fg = accent },
    NvimTreeGitDeleted         = { fg = err },
    NeoTreeNormal              = { fg = fg, bg = bg },
    NeoTreeDirectoryName       = { fg = fg },
    NeoTreeDirectoryIcon       = { fg = accent },
    NeoTreeRootName            = { fg = accent, bold = true },
    NeoTreeGitModified         = { fg = string_ },
    NeoTreeGitAdded            = { fg = accent },
    NeoTreeGitDeleted          = { fg = err },
    OilDir                     = { fg = accent },
    OilDirIcon                 = { fg = accent },
    OilLink                    = { fg = literal, underline = true },
    OilSocket                  = { fg = literal },

    -- Bufferline
    BufferLineFill                  = { bg = bg },
    BufferLineBackground            = { fg = muted, bg = bg },
    BufferLineBufferSelected        = { fg = fg, bg = bg, bold = true },
    BufferLineBufferVisible         = { fg = muted, bg = bg },
    BufferLineSeparator             = { fg = bg, bg = bg },
    BufferLineSeparatorSelected     = { fg = bg, bg = bg },
    BufferLineIndicatorSelected     = { fg = accent, bg = bg },
    BufferLineModified              = { fg = string_, bg = bg },
    BufferLineModifiedSelected      = { fg = string_, bg = bg },

    -- Lualine fallback
    lualine_a_normal  = { fg = bg, bg = accent, bold = true },
    lualine_a_insert  = { fg = bg, bg = literal, bold = true },
    lualine_a_visual  = { fg = bg, bg = string_, bold = true },
    lualine_a_replace = { fg = bg, bg = err, bold = true },
    lualine_a_command = { fg = bg, bg = muted, bold = true },

    -- Indent / which-key / notify
    IndentBlanklineChar        = { fg = bg_alt },
    IndentBlanklineContextChar = { fg = subtle },
    IblIndent                  = { fg = bg_alt },
    IblScope                   = { fg = subtle },
    WhichKey                   = { fg = accent },
    WhichKeyGroup              = { fg = literal },
    WhichKeyDesc               = { fg = fg },
    WhichKeySeparator          = { fg = subtle },
    WhichKeyFloat              = { bg = bg_alt },
    NotifyERRORBorder          = { fg = err },
    NotifyWARNBorder           = { fg = string_ },
    NotifyINFOBorder           = { fg = accent },
    NotifyDEBUGBorder          = { fg = muted },
    NotifyTRACEBorder          = { fg = muted },
    NotifyERRORIcon            = { fg = err },
    NotifyWARNIcon             = { fg = string_ },
    NotifyINFOIcon             = { fg = accent },

    -- Markdown
    ["@markup.heading"]      = { fg = accent, bold = true },
    ["@markup.heading.1"]    = { fg = accent, bold = true },
    ["@markup.heading.2"]    = { fg = accent, bold = true },
    ["@markup.heading.3"]    = { fg = literal, bold = true },
    ["@markup.heading.4"]    = { fg = literal },
    ["@markup.link"]         = { fg = accent, underline = true },
    ["@markup.link.label"]   = { fg = accent },
    ["@markup.link.url"]     = { fg = string_, underline = true },
    ["@markup.list"]         = { fg = accent },
    ["@markup.quote"]        = { fg = muted, italic = true },
    ["@markup.raw"]          = { fg = string_ },
    ["@markup.raw.block"]    = { fg = string_ },
    ["@markup.italic"]       = { fg = fg, italic = true },
    ["@markup.strong"]       = { fg = fg, bold = true },
    ["@markup.strikethrough"]= { fg = muted, strikethrough = true },
  }
end

return M
